config/routes.rb
Rails.application.routes.draw do
  
  root :to => 'user_sessions#new'
  resources :users
  resources :user_sessions
  resources :bhpb_forms
  
  
  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout
  get 'send_mail', to: 'bhpb_forms#send_mail'

end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController

  def new
    flash[:notice] = "First time users must register before logging in."

  end

  def create
  	@user = login(params[:email], params[:password])
    if @user
      redirect_to new_bhpb_form_path, :notice => "You are Logged in"
    else
      redirect_to root_url, :alert => "Invalid Username or Password"
    end
  end

  def destroy
   logout
    redirect_to(root_url, notice: 'You are Logged out')	
  end
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/user_sessions/_form.html.erb
<%= form_tag user_sessions_path, :method => :post do %>
<div class="field">
    <%= label_tag :email %><br />
    <%= text_field_tag :email %>
  </div>
  <div class="field">
    <%= label_tag :password %><br />
    <%= password_field_tag :password %>
  </div>
  <div class="actions">
    <%= submit_tag "Login", class: "btn"%>
    <%= link_to "Register", new_user_path, class: "btn" %>
  </div>
<% end %>  

app/views/user_sessions/create.html.erb
<h1>UserSessions#create</h1>

app/views/user_sessions/new.html.erb
<% if logged_in? %>
<script type="text/javascript">
    window.location.href="/bhpb_forms/new" 
</script>
<% else %>

<h1>Login</h1>

<%= render 'form' %>


<% end %>