config/routes.rb
Rails.application.routes.draw do
  
  root :to => 'user_sessions#new'
  resources :users
  resources :user_sessions
  resources :bhpb_forms
  
  
  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout
  get 'send_mail', to: 'bhpb_forms#send_mail'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BHPB</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
      <div class="header">
        <a href="#"><span class="logo"></span></a>
        <div class="tools-bar">
          <ul>
            <% if current_user %>
              <% if current_user.user_type == "admin"%>
               <li><%= link_to "Sign Out", :logout, method: :post, class: "btn" %></li>
              <li><%= link_to "Edit Profile", edit_user_path(current_user.id), class: "btn" %></li>
              <li><%= link_to "Manage Requests", bhpb_forms_path , class: "btn" %></li>
              <li><%= link_to "Submit New Request", new_bhpb_form_path, class: "btn" %></li>
              <li>Logged in as <%= current_user.email %></li>
              <% else %>
              <li><%= link_to "Sign Out", :logout, method: :post, class: "btn" %></li>
              <li><%= link_to "Edit Profile", edit_user_path(current_user.id), class: "btn" %></li>
              <li><%= link_to "Submit New Request", new_bhpb_form_path, class: "btn" %></li>
              <li>Logged in as <%= current_user.email %></li>
              <%end%>
            <% else %>
            <li><%= link_to "Register", new_user_path, class: "btn" %></li>
            <li><%= link_to "Login", :login, class: "btn" %></li>
            <% end %>
          </ul>
        </div>
      </div>
      <div id="content-container">
        <div>
          <p id="notice"><%= flash[:notice] %></p>
          <p id="alert"><%= flash[:alert] %></p>
        </div>
        <div id="bg">
          <img src="/assets/1900-print-press.jpg" alt="">
        </div>
        
        <%= yield %>
        
      </div>
      <div class="push"></div>
    </div>
    <div class="footer">
      <div class="contacts">
        <h3>Contact</h3>
        <span class="contact-person">
          <ul>
            <li><b>Deborah Karchmer</b></li>
            <li>Email: <i>sales@bellabecho.com</i> </li>
            <li>Office: <i>713-880-8294</i></li>
            <li>Mobile: <i>713-882-2564</i></li>
          </ul>
        </span>
        <span class="contact-person">
          <ul>
            <li><b>Louise Magruder</b></li>
            <li>Email: <i>louise@bellabecho.com</i> </li>
            <li>Phone: <i>281-467-9606</i></li>
          </ul>
        </span>
      </div>
      <div class="locations">
        <ul>
          <li class="location"><br>
            <b>Office Location</b>
            2421 Hurfus Drive, Houston, Texas 77092
          </li>
          
        </ul>
      </div>
    </div>
   
  </body>
</html>